name: "Google Jules AI Code Review (Gemini 3 Pro)"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Google Jules Review"
        uses: google-github-actions/jules-pr-review@v2 
        with:
          api-key: ${{ secrets.JULES_API_KEY }}
          model: "gemini-3-pro-latest" 
          mode: "thinking" 
          output_type: "inline-comments"